
export const logoWhite = require('./ferly_vertical_logo_reverse.png')
export const ferlyCard = require('./blank_card.png')
export const logoHorizontal = require('./ferly_horizontal_logo_reverse.png')
export const giveBlue = require('./give_icon_blue.png')
export const receiveBlue = require('./receive_icon_blue.png')
export const addBlue = require('./add_icon_blue.png')
export const spendBlue = require('./spend_icon_blue.png')
export const tutorialOne = require('./tutorial_graphic_one.png')
export const tutorialTwo = require('./tutorial_graphic_two.png')
export const tutorialThree = require('./tutorial_graphic_three.png')
export const tutorialFour = require('./ferly_card.png')
export const tutorialFive = require('./Debit.png')
export const tutorialSix = require('./tutorial_graphic_six.png')
export const viewLocations = require('./View_Locations_Button.png')
export const mailCard = require('./Mail_Card.png')
